version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev # Aponta para o arquivo de dev
    container_name: api_service_dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005" # Porta de Debug exposta para o Eclipse
    volumes:
      - .:/app # Mapeia todo o seu projeto local
      - ~/.m2:/root/.m2 # Reaproveita o cache do Maven
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - backend
    # O DEVELOP DEVE FICAR AQUI, DENTRO DA API:
    develop:
      watch:
        - action: sync
          path: ./target/classes
          target: /app/target/classes
        - action: restart
          path: ./pom.xml

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    ports:
      - "6050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
